# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: builtinextension 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "builtinextension"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["ippei94da"]
  s.date = "2015-07-17"
  s.description = "Personally frequently used methods for builtin classes,\n    e.g., String, Array, etc.\n    These methods are not implemented in Ruby and\n    are doubted to offer to be implemented into Ruby core system.\n    A main target is my personal programming.\n  "
  s.email = "ippei94da@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGES",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "builtinextension.gemspec",
    "lib/array/includeeql.rb",
    "lib/array/selectindices.rb",
    "lib/float/equalindelta.rb",
    "lib/string/color.rb",
    "lib/string/escapezsh.rb",
    "lib/string/mismatch.rb",
    "lib/string/splitparens.rb",
    "lib/string/width.rb",
    "test/helper.rb",
    "test/print_color",
    "test/test_array_include_eql.rb",
    "test/test_array_select_indices.rb",
    "test/test_float_equalindelta.rb",
    "test/test_string_color.rb",
    "test/test_string_escape_zsh.rb",
    "test/test_string_mismatch.rb",
    "test/test_string_split_parens.rb",
    "test/test_string_width.rb"
  ]
  s.homepage = "http://github.com/ippei94da/builtinextension"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Method as extension for builtin classes"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<test-unit>, ["~> 3.1.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.10.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.9.0"])
    else
      s.add_dependency(%q<test-unit>, ["~> 3.1.2"])
      s.add_dependency(%q<rdoc>, ["~> 4.2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.10.5"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.9.0"])
    end
  else
    s.add_dependency(%q<test-unit>, ["~> 3.1.2"])
    s.add_dependency(%q<rdoc>, ["~> 4.2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.10.5"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.9.0"])
  end
end

