# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "builtinextension"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ippei94da"]
  s.date = "2014-08-29"
  s.description = "Personally frequently used methods for builtin classes,\n    e.g., String, Array, etc.\n    These methods are not implemented in Ruby and\n    are doubted to offer to be implemented into Ruby core system.\n    A main target is my personal programming.\n  "
  s.email = "ippei94da@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGES",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/array/includeeql.rb",
    "lib/array/selectindices.rb",
    "lib/string/color.rb",
    "lib/string/escapezsh.rb",
    "lib/string/mismatch.rb",
    "lib/string/splitparens.rb",
    "lib/string/width.rb",
    "spec/array_include_eql_spec.rb",
    "spec/array_select_indices_spec.rb",
    "spec/print_color",
    "spec/spec_helper.rb",
    "spec/string_color_spec.rb",
    "spec/string_escape_zsh_spec.rb",
    "spec/string_mismatch_spec.rb",
    "spec/string_split_parens_spec.rb",
    "spec/string_width_spec.rb"
  ]
  s.homepage = "http://github.com/ippei94da/builtinextension"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Method as extension for builtin classes"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.0.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.7.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.9.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_dependency(%q<rdoc>, ["~> 4.0.1"])
      s.add_dependency(%q<bundler>, ["~> 1.7.2"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.9.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.13.0"])
    s.add_dependency(%q<rdoc>, ["~> 4.0.1"])
    s.add_dependency(%q<bundler>, ["~> 1.7.2"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.9.0"])
  end
end

